---
application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://127.0.0.1"
  sender_email: "test@gmail.com"
  authorization_token: "POSTMARK_API_TOKEN"
  timeout_milliseconds: 3000
